spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=student
spring.rabbitmq.password=student
order.rabbitmq.queue=order.queue
restaurant.rabbitmq.exchange=restaurant.direct
restaurant.rabbitmq.routingkey=to.serve
server.port=0